In [1]:
import numpy as np

In [2]:
from typing import Tuple
import torch

In [3]:
def norm(
    x: torch.Tensor,
    dim: Tuple[int], #0 이면 Layer, 1이면 Batch Normalization
    eps: float = 0.00001
) -> torch.Tensor:
    mean = torch.mean(x, dim=dim, keepdim=True)
    var = torch.square(x - mean).mean(dim=dim, keepdim=True)
    return (x - mean) / torch.sqrt(var + eps)

In [4]:
a = torch.tensor(np.arange(12),dtype=torch.float32)

In [5]:
a = a.reshape(3,4)

In [6]:
a

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

### Batch : 행

In [7]:
a[0]

tensor([0., 1., 2., 3.])

In [8]:
norm(a,(1))

tensor([[-1.3416, -0.4472,  0.4472,  1.3416],
        [-1.3416, -0.4472,  0.4472,  1.3416],
        [-1.3416, -0.4472,  0.4472,  1.3416]])

### Layer : 열

In [9]:
a[:,0]

tensor([0., 4., 8.])

In [10]:
norm(a,(0))

tensor([[-1.2247, -1.2247, -1.2247, -1.2247],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 1.2247,  1.2247,  1.2247,  1.2247]])