In [1]:
import numpy as np

In [95]:
from typing import Tuple
import torch

In [124]:
def norm(
    x: torch.Tensor,
    dim: Tuple[int],
    eps: float = 0.00001
) -> torch.Tensor:
    mean = torch.mean(x, dim=dim, keepdim=True)
    var = torch.square(x - mean).mean(dim=dim, keepdim=True)
    return (x - mean) / torch.sqrt(var + eps)

In [117]:
a = torch.tensor(np.arange(12),dtype=torch.float32)

In [118]:
a = a.reshape(3,4)

In [119]:
a

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

### Batch : 행

In [72]:
a[0]

tensor([0., 1., 2., 3.])

In [76]:
(0 - a0_mean)/a0_std

tensor(-1.1619)

In [79]:
(1 - a0_mean)/a0_std

tensor(-0.3873)

In [80]:
(2 - a0_mean)/a0_std

tensor(0.3873)

In [81]:
(3 - a0_mean)/a0_std

tensor(1.1619)

In [109]:
layer_norm(a[0],(0))

tensor([-1.3416, -0.4472,  0.4472,  1.3416])

In [90]:
layer_norm(a[1],(0))

tensor([-1.3416, -0.4472,  0.4472,  1.3416])

In [121]:
layer_norm(a[2],(0))

tensor([-1.3416, -0.4472,  0.4472,  1.3416])

In [126]:
norm(a,(1))

tensor([[-1.3416, -0.4472,  0.4472,  1.3416],
        [-1.3416, -0.4472,  0.4472,  1.3416],
        [-1.3416, -0.4472,  0.4472,  1.3416]])

### Layer : 열

In [120]:
a[:,0]

tensor([0., 4., 8.])

In [105]:
layer_norm(a,(0))

tensor([[-1.2247, -1.2247, -1.2247, -1.2247],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 1.2247,  1.2247,  1.2247,  1.2247]])